INSERT INTO PESSOA (NOME,DATA_NASCIMENTO) VALUES('Jean lucas solano','1999-09-09');
INSERT INTO PESSOA (NOME,DATA_NASCIMENTO) VALUES('Carlos Peres','1999-09-09');
INSERT INTO PESSOA (NOME,DATA_NASCIMENTO) VALUES('Lucas Fortes','1999-09-09');
INSERT INTO PESSOA (NOME,DATA_NASCIMENTO) VALUES('Leonardo Gomes','1999-09-09');

INSERT INTO ENDERECO(CEP,CIDADE,LOGRADOURO,NUMERO,TIPO_ENDERECO,ID_PESSOA) VALUES('87.125-021','CUIBA','CASA 2 QUADRA 4',10,'P',1);
INSERT INTO ENDERECO(CEP,CIDADE,LOGRADOURO,NUMERO,TIPO_ENDERECO,ID_PESSOA) VALUES('78.135-021','VARZEA GRANDE','CASA 2/3',11,'P',2);
INSERT INTO ENDERECO(CEP,CIDADE,LOGRADOURO,NUMERO,TIPO_ENDERECO,ID_PESSOA) VALUES('78.145-021','SINOP','RUA CARLOS',12,'P',3);
INSERT INTO ENDERECO(CEP,CIDADE,LOGRADOURO,NUMERO,TIPO_ENDERECO,ID_PESSOA) VALUES('78.155-021','CUIABA','COABE 32',13,'P',4);
INSERT INTO ENDERECO(CEP,CIDADE,LOGRADOURO,NUMERO,TIPO_ENDERECO,ID_PESSOA) VALUES('78.125-021','MIMOZO','LOTE 4',11,'S',1);

-- SELECT * FROM ENDERECO LEFT JOIN PESSOA ON ENDERECO.ID_PESSOA = PESSOA.ID