INSERT INTO PESSOA (ID,NOME,DATA_NASCIMENTO) VALUES(1,'Jean lucas solano','1999-09-09');
INSERT INTO PESSOA (ID,NOME,DATA_NASCIMENTO) VALUES(2,'Carlos Peres','1999-09-09');
INSERT INTO PESSOA (ID,NOME,DATA_NASCIMENTO) VALUES(3,'Lucas Fortes','1999-09-09');
INSERT INTO PESSOA (ID,NOME,DATA_NASCIMENTO) VALUES(4,'Leonardo Gomes','1999-09-09');


INSERT INTO ENDERECO(ID,CEP,CIDADE,LOGRADOURO,NUMERO,TIPO_ENDERECO,ID_PESSOA) VALUES(1,'78.125-021','CUIBA','CASA 2 QUADRA 4',10,'P',1);
INSERT INTO ENDERECO(ID,CEP,CIDADE,LOGRADOURO,NUMERO,TIPO_ENDERECO,ID_PESSOA) VALUES(2,'78.135-021','VARZEA GRANDE','CASA 2/3',11,'P',2);
INSERT INTO ENDERECO(ID,CEP,CIDADE,LOGRADOURO,NUMERO,TIPO_ENDERECO,ID_PESSOA) VALUES(3,'78.145-021','SINOP','RUA CARLOS',12,'P',3);
INSERT INTO ENDERECO(ID,CEP,CIDADE,LOGRADOURO,NUMERO,TIPO_ENDERECO,ID_PESSOA) VALUES(4,'78.155-021','CUIABA','COABE 32',13,'P',4);

-- SELECT * FROM ENDERECO LEFT JOIN PESSOA ON ENDERECO.ID_PESSOA = PESSOA.ID